import type { Metadata } from "next";
import "./globals.css";
import { Chakra_Petch, Gowun_Dodum } from "next/font/google";

const chakraPetch = Chakra_Petch({ weight: ["300", "500", "700"], subsets: ["latin"] });
const gowunDodum = Gowun_Dodum({ weight: ["400"], subsets: ["latin"], variable: "--gowun" });
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${chakraPetch.className} ${gowunDodum.variable}`}>{children}</body>
        </html>
    );
}
