import type { Metadata } from "next";
import "./globals.css";
import { Chakra_Petch } from "next/font/google";

const chakraPetch = Chakra_Petch({ weight: ['300', '500', '700'], subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={chakraPetch.className}>{children}</body>
    </html>
  );
}
